name: Node.js CI

on:
    push:
        branches: [main]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Install Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '19.9.0'

            - name: Install dependencies
              run: npm install

            - name: Build client
              run: cd client && yarn install && yarn build

            - name: Build server
              run: cd server && yarn install && yarn build

            - name: Deploy to Azure Web App
              uses: azure/webapps-deploy@v2
              with:
                  app-name: <your-app-name>
                  slot-name: <your-slot-name>
                  publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
                  package: .
                  start-command: 'node server/dist/server.js'
